<?php

namespace Mautic\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20170310201400 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE inbound_message_channels DROP FOREIGN KEY FK_ECC49674537A1329');
        $this->addSql('DROP TABLE inbound_form_results_10_contacteno');
        $this->addSql('DROP TABLE inbound_form_results_11_contacto_p');
        $this->addSql('DROP TABLE inbound_form_results_12_participa');
        $this->addSql('DROP TABLE inbound_form_results_13_consultano');
        $this->addSql('DROP TABLE inbound_form_results_14_contacto');
        $this->addSql('DROP TABLE inbound_form_results_15_consulta_p');
        $this->addSql('DROP TABLE inbound_form_results_16_inscripcio');
        $this->addSql('DROP TABLE inbound_form_results_17_contactos');
        $this->addSql('DROP TABLE inbound_form_results_18_contacto');
        $this->addSql('DROP TABLE inbound_form_results_19_registro_a');
        $this->addSql('DROP TABLE inbound_form_results_1_asdad');
        $this->addSql('DROP TABLE inbound_form_results_20_registro_n');
        $this->addSql('DROP TABLE inbound_form_results_21_consulta_e');
        $this->addSql('DROP TABLE inbound_form_results_22_subscripci');
        $this->addSql('DROP TABLE inbound_form_results_23_formulario');
        $this->addSql('DROP TABLE inbound_form_results_24_registro_p');
        $this->addSql('DROP TABLE inbound_form_results_25_inscripcio');
        $this->addSql('DROP TABLE inbound_form_results_26_subscripci');
        $this->addSql('DROP TABLE inbound_form_results_27_contacteno');
        $this->addSql('DROP TABLE inbound_form_results_28_brochure');
        $this->addSql('DROP TABLE inbound_form_results_29_contacto_p');
        $this->addSql('DROP TABLE inbound_form_results_30_contacteno');
        $this->addSql('DROP TABLE inbound_form_results_31_home__cont');
        $this->addSql('DROP TABLE inbound_form_results_32_catalago_p');
        $this->addSql('DROP TABLE inbound_form_results_33_contacto');
        $this->addSql('DROP TABLE inbound_form_results_34_servicio');
        $this->addSql('DROP TABLE inbound_form_results_35_contacto');
        $this->addSql('DROP TABLE inbound_form_results_36_contacto');
        $this->addSql('DROP TABLE inbound_form_results_37_puntos_de');
        $this->addSql('DROP TABLE inbound_form_results_38_formulario');
        $this->addSql('DROP TABLE inbound_form_results_39_landing_ca');
        $this->addSql('DROP TABLE inbound_form_results_40_landing_es');
        $this->addSql('DROP TABLE inbound_form_results_41_landing_es');
        $this->addSql('DROP TABLE inbound_form_results_42_landing_ho');
        $this->addSql('DROP TABLE inbound_form_results_43_landing_pi');
        $this->addSql('DROP TABLE inbound_form_results_44_plan_mio_m');
        $this->addSql('DROP TABLE inbound_form_results_45_form_conta');
        $this->addSql('DROP TABLE inbound_form_results_46_form_linea');
        $this->addSql('DROP TABLE inbound_form_results_47_form_produ');
        $this->addSql('DROP TABLE inbound_form_results_48_form_catal');
        $this->addSql('DROP TABLE inbound_form_results_50_descarga_e');
        $this->addSql('DROP TABLE inbound_form_results_51_promo');
        $this->addSql('DROP TABLE inbound_form_results_52_ofertas');
        $this->addSql('DROP TABLE inbound_form_results_54_landing_ba');
        $this->addSql('DROP TABLE inbound_form_results_55_landing_ca');
        $this->addSql('DROP TABLE inbound_form_results_56_landing_ca');
        $this->addSql('DROP TABLE inbound_form_results_57_landing_ca');
        $this->addSql('DROP TABLE inbound_form_results_58_landing_ca');
        $this->addSql('DROP TABLE inbound_form_results_59_landing_ca');
        $this->addSql('DROP TABLE inbound_form_results_60_landing_cl');
        $this->addSql('DROP TABLE inbound_form_results_61_landing_cl');
        $this->addSql('DROP TABLE inbound_form_results_62_landing_cl');
        $this->addSql('DROP TABLE inbound_form_results_63_landing_co');
        $this->addSql('DROP TABLE inbound_form_results_64_landing_co');
        $this->addSql('DROP TABLE inbound_form_results_65_landing_fi');
        $this->addSql('DROP TABLE inbound_form_results_66_landing_ho');
        $this->addSql('DROP TABLE inbound_form_results_67_landing_la');
        $this->addSql('DROP TABLE inbound_form_results_68_lomas_de_m');
        $this->addSql('DROP TABLE inbound_form_results_69_landing_mi');
        $this->addSql('DROP TABLE inbound_form_results_70_landing_pl');
        $this->addSql('DROP TABLE inbound_form_results_71_landing_po');
        $this->addSql('DROP TABLE inbound_form_results_72_landing_ri');
        $this->addSql('DROP TABLE inbound_form_results_73_landing_sa');
        $this->addSql('DROP TABLE inbound_form_results_74_landing_sa');
        $this->addSql('DROP TABLE inbound_form_results_75_landing_so');
        $this->addSql('DROP TABLE inbound_form_results_76_landing_te');
        $this->addSql('DROP TABLE inbound_form_results_77_landing_to');
        $this->addSql('DROP TABLE inbound_form_results_78_consultas');
        $this->addSql('DROP TABLE inbound_form_results_79_newsletter');
        $this->addSql('DROP TABLE inbound_form_results_80_consulta_b');
        $this->addSql('DROP TABLE inbound_form_results_81_landing_cu');
        $this->addSql('DROP TABLE inbound_form_results_83_plan_canje');
        $this->addSql('DROP TABLE inbound_form_results_84_landing_ca');
        $this->addSql('DROP TABLE inbound_form_results_85_cupon');
        $this->addSql('DROP TABLE inbound_form_results_86_landing_ti');
        $this->addSql('DROP TABLE inbound_form_results_88_expoagro');
        $this->addSql('DROP TABLE inbound_lead_categories');
        $this->addSql('DROP TABLE inbound_message_channels');
        $this->addSql('DROP TABLE inbound_messages');
        $this->addSql('DROP TABLE inbound_plugin_citrix_events');
        $this->addSql('DROP TABLE inbound_saml_id_entry');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE inbound_form_results_10_contacteno (submission_id INT NOT NULL, form_id INT NOT NULL, attr_268 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_269 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_270 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_271 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_CBB05ABBE1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_11_contacto_p (submission_id INT NOT NULL, form_id INT NOT NULL, attr_272 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_273 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_274 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_275 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_276 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_16D79945E1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_12_participa (submission_id INT NOT NULL, form_id INT NOT NULL, attr_277 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_278 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_279 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_280 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_281 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_282 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_283 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_25D2E463E1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_13_consultano (submission_id INT NOT NULL, form_id INT NOT NULL, attr_196 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_197 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_200 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_198 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_199 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_6497C945E1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_14_contacto (submission_id INT NOT NULL, form_id INT NOT NULL, attr_314 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_315 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_316 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_317 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_DE8D05C1E1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_15_consulta_p (submission_id INT NOT NULL, form_id INT NOT NULL, attr_184 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_185 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_186 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_187 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_C0FF66E2E1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_16_inscripcio (submission_id INT NOT NULL, form_id INT NOT NULL, attr_179 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_180 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_181 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_182 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_183 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_6A4FE8DDE1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_17_contactos (submission_id INT NOT NULL, form_id INT NOT NULL, attr_108 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_109 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_110 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, provincia LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_112 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_113 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_114 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_6E51D629E1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_18_contacto (submission_id INT NOT NULL, form_id INT NOT NULL, attr_63 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_77 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_78 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_79 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_80 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_81 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_82 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_83 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, provincia LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_85 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_C4B1E54FE1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_19_registro_a (submission_id INT NOT NULL, form_id INT NOT NULL, attr_161 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_162 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_163 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_164 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, dni LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_229 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_165 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_166 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_167 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_341 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_342 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_87DAFEFAE1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_1_asdad (submission_id INT NOT NULL, form_id INT NOT NULL, UNIQUE INDEX UNIQ_8AFCCF93E1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_20_registro_n (submission_id INT NOT NULL, form_id INT NOT NULL, attr_154 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_155 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_156 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_157 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_158 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_159 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_160 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_3706B534E1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_21_consulta_e (submission_id INT NOT NULL, form_id INT NOT NULL, attr_201 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_202 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_203 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_13EED5B8E1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_22_subscripci (submission_id INT NOT NULL, form_id INT NOT NULL, attr_219 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_E212E0B4E1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_23_formulario (submission_id INT NOT NULL, form_id INT NOT NULL, attr_115 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_116 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_117 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_118 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_119 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_120 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_121 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_122 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_123 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_124 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_125 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_126 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_1567817BE1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_24_registro_p (submission_id INT NOT NULL, form_id INT NOT NULL, attr_244 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_253 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_248 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_254 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_245 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_246 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_249 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_250 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_247 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_CE0FB328E1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_25_inscripcio (submission_id INT NOT NULL, form_id INT NOT NULL, attr_98 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_99 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_100 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_101 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_102 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_103 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_363 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_A01B56E3E1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_26_subscripci (submission_id INT NOT NULL, form_id INT NOT NULL, attr_243 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_E114DBCBE1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_27_contacteno (submission_id INT NOT NULL, form_id INT NOT NULL, attr_204 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_205 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_206 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_216 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_207 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_2E2DFFAE1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_28_brochure (submission_id INT NOT NULL, form_id INT NOT NULL, attr_212 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_213 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_214 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_5D403839E1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_29_contacto_p (submission_id INT NOT NULL, form_id INT NOT NULL, attr_208 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_217 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_209 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_210 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_211 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_215 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_AD118375E1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_30_contacteno (submission_id INT NOT NULL, form_id INT NOT NULL, attr_175 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_176 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_177 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_178 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_179 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_ABECEFF0E1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_31_home__cont (submission_id INT NOT NULL, form_id INT NOT NULL, attr_168 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_169 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_170 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_188 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_227 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_9712D8B7E1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_32_catalago_p (submission_id INT NOT NULL, form_id INT NOT NULL, attr_220 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_221 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, producto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_95B80329E1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_33_contacto (submission_id INT NOT NULL, form_id INT NOT NULL, attr_284 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_285 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_286 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_287 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_643DA779E1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_34_servicio (submission_id INT NOT NULL, form_id INT NOT NULL, attr_288 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_289 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_290 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_291 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_292 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_293 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_294 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_295 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_296 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_6A260716E1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_35_contacto (submission_id INT NOT NULL, form_id INT NOT NULL, attr_72 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_73 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_74 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_75 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_76 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_6923D73EE1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_36_contacto (submission_id INT NOT NULL, form_id INT NOT NULL, attr_64 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_65 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_66 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_67 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_82146C3DE1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_37_puntos_de (submission_id INT NOT NULL, form_id INT NOT NULL, attr_305 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_306 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_307 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_308 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_309 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_336 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_364D3784E1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_38_formulario (submission_id INT NOT NULL, form_id INT NOT NULL, formreferer LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, formnombre LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, formapellido LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, formtelefono LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, formemail LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, formcomentarios LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_B963FCF0E1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_39_landing_ca (submission_id INT NOT NULL, form_id INT NOT NULL, nombre_empresa LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre_form LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_usuario_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, apellido LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, tel LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, comentarios LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, campo_banner LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, banner LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_45D74411E1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_40_landing_es (submission_id INT NOT NULL, form_id INT NOT NULL, nombre_empresa LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre_form LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, apellido LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, tel LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, comentarios LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, banner LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_EEAE16E1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_41_landing_es (submission_id INT NOT NULL, form_id INT NOT NULL, nombre_empresa LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, apellido LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, tel LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, comentarios LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, banner LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_9B4BE279E1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_42_landing_ho (submission_id INT NOT NULL, form_id INT NOT NULL, nombre_empresa LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, apellido LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, tel LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, comentarios LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, banner LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_4D7A128BE1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_43_landing_pi (submission_id INT NOT NULL, form_id INT NOT NULL, nombre_empresa LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, apellido LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, tel LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, comentarios LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, banner LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_BDA76388E1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_44_plan_mio_m (submission_id INT NOT NULL, form_id INT NOT NULL, nombre_empresa LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, apellido LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, tel LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, comentarios LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, banner LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_3CF4B163E1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_45_form_conta (submission_id INT NOT NULL, form_id INT NOT NULL, attr_314 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_315 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_316 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_317 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_93EF26FBE1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_46_form_linea (submission_id INT NOT NULL, form_id INT NOT NULL, attr_322 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_323 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_334 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_324 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_325 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_326 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_10931F16E1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_47_form_produ (submission_id INT NOT NULL, form_id INT NOT NULL, attr_327 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_328 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_335 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_330 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_331 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_3311 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_AB3D766FE1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_48_form_catal (submission_id INT NOT NULL, form_id INT NOT NULL, attr_338 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_339 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_340 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_B52AEC29E1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_50_descarga_e (submission_id INT NOT NULL, form_id INT NOT NULL, nombre LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_7912743E1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_51_promo (submission_id INT NOT NULL, form_id INT NOT NULL, attr_365 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_366 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_367 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_368 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_369 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_370 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_371 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_EEBE163AE1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_52_ofertas (submission_id INT NOT NULL, form_id INT NOT NULL, attr_352 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_353 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_354 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_355 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_356 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_357 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_47AB6E9FE1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_54_landing_ba (submission_id INT NOT NULL, form_id INT NOT NULL, nombre_empresa LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre_form LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_usuario_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, apellido LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, tel LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, comentarios LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_6286AB63E1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_55_landing_ca (submission_id INT NOT NULL, form_id INT NOT NULL, nombre_empresa LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre_form LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_usuario_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, apellido LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, tel LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, comentarios LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_E038D64DE1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_56_landing_ca (submission_id INT NOT NULL, form_id INT NOT NULL, nombre_empresa LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre_form LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_usuario_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, apellido LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, tel LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, comentarios LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_97A604BDE1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_57_landing_ca (submission_id INT NOT NULL, form_id INT NOT NULL, nombre_empresa LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre_form LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_usuario_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, apellido LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, tel LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, comentarios LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_C0348D2E1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_58_landing_ca (submission_id INT NOT NULL, form_id INT NOT NULL, nombre_empresa LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre_form LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_usuario_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, apellido LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, tel LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, comentarios LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_7E97D7A3E1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_59_landing_ca (submission_id INT NOT NULL, form_id INT NOT NULL, nombre_empresa LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre_form LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_usuario_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, apellido LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, tel LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, comentarios LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_E5329BCCE1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_60_landing_cl (submission_id INT NOT NULL, form_id INT NOT NULL, nombre_empresa LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre_form LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_usuario_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, apellido LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, tel LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, comentarios LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_BBE0B12EE1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_61_landing_cl (submission_id INT NOT NULL, form_id INT NOT NULL, nombre_empresa LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre_form LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_usuario_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, apellido LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, tel LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, comentarios LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_2045FD41E1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_62_landing_cl (submission_id INT NOT NULL, form_id INT NOT NULL, nombre_empresa LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre_form LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_usuario_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, apellido LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, tel LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, comentarios LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_57DB2FB1E1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_63_landing_co (submission_id INT NOT NULL, form_id INT NOT NULL, nombre_empresa LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre_form LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_usuario_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, apellido LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, tel LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, comentarios LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_55773264E1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_64_landing_co (submission_id INT NOT NULL, form_id INT NOT NULL, nombre_empresa LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre_form LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_usuario_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, apellido LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, tel LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, comentarios LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_21EFDBEBE1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_65_landing_fi (submission_id INT NOT NULL, form_id INT NOT NULL, nombre_empresa LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre_form LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_usuario_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, apellido LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, tel LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_2E5EC6F4E1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_66_landing_ho (submission_id INT NOT NULL, form_id INT NOT NULL, nombre_empresa LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre_form LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_usuario_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, apellido LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, tel LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, comentarios LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_2E209CBFE1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_67_landing_la (submission_id INT NOT NULL, form_id INT NOT NULL, nombre_empresa LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre_form LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_usuario_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, apellido LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, tel LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, comentarios LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_365138D3E1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_68_lomas_de_m (submission_id INT NOT NULL, form_id INT NOT NULL, nombre_empresa LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre_form LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_usuario_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, apellido LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, tel LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, comentarios LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_A828020CE1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_69_landing_mi (submission_id INT NOT NULL, form_id INT NOT NULL, nombre_empresa LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre_form LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_usuario_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, apellido LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, tel LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, comentarios LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_C8A052BEE1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_70_landing_pl (submission_id INT NOT NULL, form_id INT NOT NULL, nombre_empresa LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre_form LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_usuario_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, apellido LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, tel LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, comentarios LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_7992939E1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_71_landing_po (submission_id INT NOT NULL, form_id INT NOT NULL, nombre_empresa LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre_form LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_usuario_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, apellido LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, tel LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, comentarios LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_53534ECE1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_72_landing_ri (submission_id INT NOT NULL, form_id INT NOT NULL, nombre_empresa LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre_form LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_usuario_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, apellido LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, tel LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, comentarios LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_A9FE21ABE1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_73_landing_sa (submission_id INT NOT NULL, form_id INT NOT NULL, nombre_empresa LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre_form LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_usuario_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, apellido LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, tel LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, comentarios LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_259BD4B7E1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_74_landing_sa (submission_id INT NOT NULL, form_id INT NOT NULL, nombre_empresa LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre_form LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_usuario_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, apellido LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, tel LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, comentarios LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_51033D38E1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_75_landing_so (submission_id INT NOT NULL, form_id INT NOT NULL, nombre_empresa LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre_form LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_usuario_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, apellido LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, tel LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, comentarios LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_2D1E5C50E1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_76_landing_te (submission_id INT NOT NULL, form_id INT NOT NULL, nombre_empresa LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre_form LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_usuario_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, apellido LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, tel LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, comentarios LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_F514F179E1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_77_landing_to (submission_id INT NOT NULL, form_id INT NOT NULL, nombre_empresa LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre_form LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email_usuario_asunto LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, nombre LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, apellido LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, tel LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, comentarios LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_8E645408E1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_78_consultas (submission_id INT NOT NULL, form_id INT NOT NULL, attr_193 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_195 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_5C11BB2DE1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_79_newsletter (submission_id INT NOT NULL, form_id INT NOT NULL, UNIQUE INDEX UNIQ_9EB7307CE1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_80_consulta_b (submission_id INT NOT NULL, form_id INT NOT NULL, attr_386 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_387 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_388 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_389 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_2C706A52E1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_81_landing_cu (submission_id INT NOT NULL, form_id INT NOT NULL, nombre LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, apellido LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, idioma LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_BEC85931E1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_83_plan_canje (submission_id INT NOT NULL, form_id INT NOT NULL, nombre LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, apellido LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, telefono LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_57A572AE1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_84_landing_ca (submission_id INT NOT NULL, form_id INT NOT NULL, nombre LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, apellido LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, email LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, idioma LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_3CB1FA5CE1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_85_cupon (submission_id INT NOT NULL, form_id INT NOT NULL, attr_412 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_414 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_413 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_6928444AE1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_86_landing_ti (submission_id INT NOT NULL, form_id INT NOT NULL, tipoidioma LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, idiomasel LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_DBD26867E1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_form_results_88_expoagro (submission_id INT NOT NULL, form_id INT NOT NULL, attr_423 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_424 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_425 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_426 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_427 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_428 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, attr_429 LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_A455BA2FE1FD49335FF69B7D (submission_id, form_id), PRIMARY KEY(submission_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_lead_categories (id INT AUTO_INCREMENT NOT NULL, category_id INT NOT NULL, lead_id INT NOT NULL, date_added DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', manually_removed TINYINT(1) NOT NULL, manually_added TINYINT(1) NOT NULL, INDEX IDX_8817CB2B55458D (lead_id), INDEX IDX_8817CB2B12469DE2 (category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_message_channels (id INT AUTO_INCREMENT NOT NULL, message_id INT NOT NULL, channel VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, channel_id INT DEFAULT NULL, properties LONGTEXT NOT NULL COLLATE utf8_unicode_ci COMMENT \'(DC2Type:json_array)\', is_enabled TINYINT(1) NOT NULL, UNIQUE INDEX inbound_channel_index (message_id, channel), INDEX IDX_ECC49674537A1329 (message_id), INDEX inbound_channel_entity_index (channel, channel_id), INDEX inbound_channel_enabled_index (channel, is_enabled), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_messages (id INT AUTO_INCREMENT NOT NULL, category_id INT DEFAULT NULL, is_published TINYINT(1) NOT NULL, date_added DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', created_by INT DEFAULT NULL, created_by_user VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, date_modified DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', modified_by INT DEFAULT NULL, modified_by_user VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, checked_out DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', checked_out_by INT DEFAULT NULL, checked_out_by_user VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, name VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, description LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, publish_up DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', publish_down DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', INDEX IDX_967071FD12469DE2 (category_id), INDEX inbound_date_message_added (date_added), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_plugin_citrix_events (id INT AUTO_INCREMENT NOT NULL, lead_id INT NOT NULL, product VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, email VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, event_name VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, event_desc VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, event_type VARCHAR(50) NOT NULL COLLATE utf8_unicode_ci, event_date DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', INDEX inbound_citrix_event_email (product, email), INDEX inbound_citrix_event_name (product, event_name, event_type), INDEX inbound_citrix_event_type (product, event_type, event_date), INDEX inbound_citrix_event_product (product, email, event_type), INDEX inbound_citrix_event_product_name (product, email, event_type, event_name), INDEX inbound_citrix_event_product_name_lead (product, event_type, event_name, lead_id), INDEX inbound_citrix_event_product_type_lead (product, event_type, lead_id), INDEX inbound_citrix_event_date (event_date), INDEX IDX_4AFA681D55458D (lead_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbound_saml_id_entry (id VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, entity_id VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, expiryTimestamp INT NOT NULL, PRIMARY KEY(id, entity_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE inbound_lead_categories ADD CONSTRAINT FK_8817CB2B12469DE2 FOREIGN KEY (category_id) REFERENCES inbound_categories (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE inbound_lead_categories ADD CONSTRAINT FK_8817CB2B55458D FOREIGN KEY (lead_id) REFERENCES inbound_leads (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE inbound_message_channels ADD CONSTRAINT FK_ECC49674537A1329 FOREIGN KEY (message_id) REFERENCES inbound_messages (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE inbound_messages ADD CONSTRAINT FK_967071FD12469DE2 FOREIGN KEY (category_id) REFERENCES inbound_categories (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE inbound_plugin_citrix_events ADD CONSTRAINT FK_4AFA681D55458D FOREIGN KEY (lead_id) REFERENCES inbound_leads (id) ON DELETE CASCADE');
    }
}
